In [3]:
# LABEL ENCODING
from sklearn.preprocessing import LabelEncoder
y = ['cat','dog','cat','bird']
le = LabelEncoder()
y_encoded = le.fit_transform(y)
print(y_encoded)

[1 2 1 0]


In [10]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
df = pd.DataFrame({'color':['red','blue','green','red','blue']}
# sparse_output=False returns a dense numpy array ; set_output returns a pamdas dataframe
df_encoded = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
df_encoded = encoder.fit_transform(df[['color']])
print(df_encoded)

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0


In [11]:
# handle missing values
import pandas as pd

data = {
    'Name': ['Ram', 'Kamal', 'Ajay'],
    'Age': [25, None, 32],
    'Salary': [5000, 6000, None]
}

df = pd.DataFrame(data)

print("Original Dataframe")
print(df)

# Find null values
print(df.isnull().sum())

# Drop rows with null values
df_drop = df.dropna()
print(df_drop)

# Fill missing values with mean
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

print(df)

Original Dataframe
    Name   Age  Salary
0    Ram  25.0  5000.0
1  Kamal   NaN  6000.0
2   Ajay  32.0     NaN
Name      0
Age       1
Salary    1
dtype: int64
  Name   Age  Salary
0  Ram  25.0  5000.0
    Name   Age  Salary
0    Ram  25.0  5000.0
1  Kamal  28.5  6000.0
2   Ajay  32.0  5500.0


In [12]:
# handle missing values
import pandas as pd
import numpy as np
data = {
"colors":['red','green','blue','orange','green','blue',np.nan]
}
df = pd.DataFrame(data)
# print(df)

# handle null values
df.dropna(inplace=True)
print(df)

   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue


In [13]:
# label encoding
from sklearn.preprocessing import LabelEncoder

# method 1
le = LabelEncoder()
df['colors_encoder1'] = le.fit_transform(df['colors'])

# method 2
df['colors_encoder2'] = LabelEncoder().fit_transform(df['colors'])
# print(df)

# method 3
import sklearn
df['colors_encoder3'] = sklearn.preprocessing.LabelEncoder().fit_transform(df['colors'])
print(df)

   colors  colors_encoder1  colors_encoder2  colors_encoder3
0     red                3                3                3
1   green                1                1                1
2    blue                0                0                0
3  orange                2                2                2
4   green                1                1                1
5    blue                0                0                0


In [14]:
# one hot encoding
from sklearn.preprocessing import OneHotEncoder
print(df)

# drop cols of label encoding
if'colors_encoder' in df.keys():
 df.drop(df[['colors_encoder','colors_encoder1','colors_encoder2','colors_encoder3']],axis=1,inplace=True)

print(df)

# one hot encoding

   colors  colors_encoder1  colors_encoder2  colors_encoder3
0     red                3                3                3
1   green                1                1                1
2    blue                0                0                0
3  orange                2                2                2
4   green                1                1                1
5    blue                0                0                0
   colors  colors_encoder1  colors_encoder2  colors_encoder3
0     red                3                3                3
1   green                1                1                1
2    blue                0                0                0
3  orange                2                2                2
4   green                1                1                1
5    blue                0                0                0


In [15]:
# one hot encoding
from sklearn.preprocessing import OneHotEncoder
print(df)

# drop cols of label encoding
if 'colors_encoder1' in df.keys():
   df.drop(df[['colors_encoder1','colors_encoder2','colors_encoder3']],axis=1,inplace=True)

print(df)

encoder = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
df_encoded = encoder.fit_transform(df[['colors']])
print(df_encoded)

# by help of sklearn
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['colors']])
print(encoded.toarray())


# one hot encoding by help of pandas
# df_encoder = pd.get_dummies(df,coloums=['colors'])
# print(df_encoder)

   colors  colors_encoder1  colors_encoder2  colors_encoder3
0     red                3                3                3
1   green                1                1                1
2    blue                0                0                0
3  orange                2                2                2
4   green                1                1                1
5    blue                0                0                0
   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
   colors_blue  colors_green  colors_orange  colors_red
0          0.0           0.0            0.0         1.0
1          0.0           1.0            0.0         0.0
2          1.0           0.0            0.0         0.0
3          0.0           0.0            1.0         0.0
4          0.0           1.0            0.0         0.0
5          1.0           0.0            0.0         0.0
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [24]:
# Combination of -> H.m.v | L.E | O.H.E

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
data = {
    "age":[10,20,np.nan,26,30],
    "gender":['male','female','others','male',np.nan],
    "name":['raj','priya','yash','hello','veer']
}

df = pd.DataFrame(data)
print(df)

# Handle missing values
df['age'] = df['age'].fillna(df['age'].mean())
df.dropna(subset=['gender'],inplace=True)
print(df)

#label Encoding
le= LabelEncoder()
df['gender']= le.fit_transform(df['gender'])
print(df)

# one hot encoder
oe= OneHotEncoder()
oe_e= oe.fit_transform(df[['gender']]).toarray()
print(oe_e)

    age  gender   name
0  10.0    male    raj
1  20.0  female  priya
2   NaN  others   yash
3  26.0    male  hello
4  30.0     NaN   veer
    age  gender   name
0  10.0    male    raj
1  20.0  female  priya
2  21.5  others   yash
3  26.0    male  hello
    age  gender   name
0  10.0       1    raj
1  20.0       0  priya
2  21.5       2   yash
3  26.0       1  hello
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
