In [16]:
# polynomial regression
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# data
df = pd.DataFrame({
    "Experience" :[1,2,3,4,5]
})

x = df
y = [10,20,50,90,150]

# poly feature
poly = PolynomialFeatures(degree=2)
x_poly = poly.fit_transform(x)
print(x_poly)


# model
model = LinearRegression()
model.fit(x_poly,y)

# prediction
input_data = int(input('Enter the experience:'))
new_data = pd.DataFrame({
    'Experience':[input_data]
})

# convert new data to poly
u_new_data = poly.fit_transform(new_data)
predicted_data = model.predict(u_new_data)
print(predicted_data)


[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]
Enter the experience:10
[678.28571429]


In [2]:
###  LINEAR REGRESSION  -> under fitting
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.DataFrame({
    "Label" :[1,2,3,4,5]
})
x = df
y = [10,20,50,90,150]

#model
model = LinearRegression()
model.fit(x,y)

# prediction
input_data = int(input('Enter the label:'))
new_data = pd.DataFrame({
    'Label':[input_data]
})
predicted_data = model.predict(new_data)
print(predicted_data[0])




Enter the label:12
379.0000000000001
